// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Service extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'cloudrun:index:Service';

    /**
     * Returns true if the given object is an instance of Service.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Service {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Service.__pulumiType;
    }

    /**
     * The Docker image of the service
     */
    public /*out*/ readonly imageRef!: pulumi.Output<string>;
    /**
     * The URL of the deployed service.
     */
    public /*out*/ readonly url!: pulumi.Output<string | undefined>;

    /**
     * Create a Service resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if ((!args || args.region === undefined) && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["appPath"] = args ? args.appPath : undefined;
            resourceInputs["concurrency"] = args ? args.concurrency : undefined;
            resourceInputs["containerPort"] = args ? args.containerPort : undefined;
            resourceInputs["cpu"] = args ? args.cpu : undefined;
            resourceInputs["imageName"] = args ? args.imageName : undefined;
            resourceInputs["memory"] = args ? args.memory : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["imageRef"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        } else {
            resourceInputs["imageRef"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Service.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Service resource.
 */
export interface ServiceArgs {
    /**
     * The path to the application source code.
     */
    appPath?: pulumi.Input<string>;
    /**
     * The number of concurrent containers to run.
     */
    concurrency?: pulumi.Input<number>;
    /**
     * The port the container listens on.
     */
    containerPort?: pulumi.Input<number>;
    /**
     * The CPU limit for the container.
     */
    cpu?: pulumi.Input<number>;
    /**
     * The name of the Docker image.
     */
    imageName?: pulumi.Input<string>;
    /**
     * The memory limit for the container.
     */
    memory?: pulumi.Input<string>;
    /**
     * The project to deploy the service to. The project requires the Artifact
     *     Registry API and the Cloud Run API to be enabled.
     */
    project: pulumi.Input<string>;
    /**
     * The region to deploy the service to.
     */
    region: pulumi.Input<string>;
}
